<?
$PERM["orders"]["G2"]="D";
$PERM["orders"]["G3"]="D";
$PERM["orders"]["G4"]="D";
$PERM["orders"]["G7"]="D";
$PERM["orders"]["G27"]="D";
$PERM["orders"]["G28"]="D";
$PERM["orders"]["G22"]="D";
$PERM["orders"]["G9"]="D";
$PERM["orders"]["G16"]="R";
$PERM["orders"]["G8"]="D";
$PERM["orders"]["G5"]="D";
$PERM["orders"]["G15"]="D";
$PERM["orders"]["G20"]="D";
$PERM["orders"]["G21"]="D";
$PERM["orders"]["G10"]="D";
$PERM["orders"]["G12"]="R";
$PERM["orders"]["*"]="D";
?>