<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Diada-arms.ru");
?> 

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"catalog", 
	array(
		"ACTION_VARIABLE" => "action",
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_PICT_PROP" => "ADD_PHOTOS",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BASKET_URL" => "/personal/cart/",
        "BIG_DATA_RCM_TYPE" => "any",
        "CACHE_FILTER" => "Y",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "360002",
        "CACHE_TYPE" => "A",
        "COMMON_ADD_TO_BASKET_ACTION" => "",
        "COMMON_SHOW_CLOSE_POPUP" => "N",
        "CONVERT_CURRENCY" => "N",
        "DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
        "DETAIL_ADD_TO_BASKET_ACTION" => array(
            0 => "BUY",
        ),
        "DETAIL_BACKGROUND_IMAGE" => "-",
        "DETAIL_BRAND_USE" => "N",
        "DETAIL_BROWSER_TITLE" => "-",
        "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
        "DETAIL_DETAIL_PICTURE_MODE" => "IMG",
        "DETAIL_DISPLAY_NAME" => "Y",
        "DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
        "DETAIL_META_DESCRIPTION" => "-",
        "DETAIL_META_KEYWORDS" => "-",
        "DETAIL_PROPERTY_CODE" => array(
            0 => "SET_BASE",
            1 => "SET_MASTER",
            2 => "",
        ),
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
        "DETAIL_SHOW_MAX_QUANTITY" => "N",
        "DETAIL_USE_COMMENTS" => "N",
        "DETAIL_USE_VOTE_RATING" => "N",
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "ELEMENT_SORT_FIELD" => "sort",
        "ELEMENT_SORT_FIELD2" => "id",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_ORDER2" => "desc",
        "FILE_404" => "",
        "FILTER_VIEW_MODE" => "VERTICAL",
        "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
        "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
        "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
        "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
        "GIFTS_MESS_BTN_BUY" => "Выбрать",
        "GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
        "GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
        "GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
        "GIFTS_SHOW_IMAGE" => "Y",
        "GIFTS_SHOW_NAME" => "Y",
        "GIFTS_SHOW_OLD_PRICE" => "Y",
        "HIDE_NOT_AVAILABLE" => "N",
        "IBLOCK_ID" => FCbit\Conf::FCbit_CATALOG_IBLOCK_ID,
        "IBLOCK_TYPE" => "ibCatalog",
        "INCLUDE_SUBSECTIONS" => "Y",
        "INSTANT_RELOAD" => "N",
        "LABEL_PROP" => "-",
        "LINE_ELEMENT_COUNT" => "3",
        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
        "LINK_IBLOCK_ID" => "",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_PROPERTY_SID" => "",
        "LIST_BROWSER_TITLE" => "-",
        "LIST_META_DESCRIPTION" => "-",
        "LIST_META_KEYWORDS" => "-",
        "LIST_PROPERTY_CODE" => array(
            0 => "kalibr_mm",
            1 => "",
        ),
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_COMPARE" => "Сравнение",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "lazyload",
        "PAGER_TITLE" => "Товары",
        "PAGE_ELEMENT_COUNT" => "30",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array(
            0 => "base",
        ),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPERTIES" => array(
        ),
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "",
        "SECTIONS_SHOW_PARENT_NAME" => "Y",
        "SECTIONS_VIEW_MODE" => "LIST",
        "SECTION_ADD_TO_BASKET_ACTION" => "ADD",
        "SECTION_BACKGROUND_IMAGE" => "-",
        "SECTION_COUNT_ELEMENTS" => "Y",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SECTION_TOP_DEPTH" => "2",
        "SEF_FOLDER" => "/catalog/",
        "SEF_MODE" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "SET_STATUS_404" => "Y",
        "SET_TITLE" => "Y",
        "SHOW_404" => "Y",
        "SHOW_DEACTIVATED" => "N",
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_TOP_ELEMENTS" => "Y",
        "SIDEBAR_DETAIL_SHOW" => "Y",
        "SIDEBAR_PATH" => "",
        "SIDEBAR_SECTION_SHOW" => "Y",
        "TEMPLATE_THEME" => "blue",
        "TOP_ADD_TO_BASKET_ACTION" => "ADD",
        "TOP_ELEMENT_COUNT" => "9",
        "TOP_ELEMENT_SORT_FIELD" => "sort",
        "TOP_ELEMENT_SORT_FIELD2" => "id",
        "TOP_ELEMENT_SORT_ORDER" => "asc",
        "TOP_ELEMENT_SORT_ORDER2" => "desc",
        "TOP_LINE_ELEMENT_COUNT" => "3",
        "TOP_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "TOP_VIEW_MODE" => "SECTION",
        "USE_ALSO_BUY" => "N",
        "USE_BIG_DATA" => "Y",
        "USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
        "USE_COMPARE" => "Y",
        "USE_ELEMENT_COUNTER" => "Y",
        "USE_FILTER" => "Y",
        "USE_GIFTS_DETAIL" => "Y",
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
        "USE_GIFTS_SECTION" => "Y",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "Y",
        "USE_REVIEW" => "N",
        "USE_SALE_BESTSELLERS" => "Y",
        "USE_STORE" => "N",
        "COMPONENT_TEMPLATE" => "catalog",
        "FILTER_NAME" => "",
        "FILTER_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "FILTER_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "FILTER_PRICE_CODE" => array(
            0 => "base",
        ),
        "COMPARE_NAME" => "CATALOG_COMPARE_LIST",
        "COMPARE_FIELD_CODE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "DETAIL_PICTURE",
            2 => "",
        ),
        "COMPARE_PROPERTY_CODE" => array(
            0 => "4523",
            1 => "4524",
            2 => "4525",
            3 => "4526",
            4 => "4527",
            5 => "4529",
            6 => "4530",
            7 => "4531",
            8 => "4532",
            9 => "4533",
            10 => "4534",
            11 => "4536",
            12 => "4537",
            13 => "4538",
            14 => "4539",
            15 => "4540",
            16 => "4541",
            17 => "4542",
            18 => "4544",
            19 => "4546",
            20 => "4548",
            21 => "4550",
            22 => "4551",
            23 => "4552",
            24 => "4553",
            25 => "4554",
            26 => "4555",
            27 => "4556",
            28 => "4557",
            29 => "4558",
            30 => "4559",
            31 => "4560",
            32 => "4561",
            33 => "4562",
            34 => "4563",
            35 => "4564",
            36 => "4597",
            37 => "4603",
            38 => "4604",
            39 => "4605",
            40 => "4606",
            41 => "4607",
            42 => "4608",
            43 => "4609",
            44 => "4610",
            45 => "4611",
            46 => "4612",
            47 => "4613",
            48 => "4614",
            49 => "4615",
            50 => "4616",
            51 => "4617",
            52 => "4618",
            53 => "4619",
            54 => "4620",
            55 => "4622",
            56 => "4623",
            57 => "usilie_natyazheniya",
            58 => "ves",
            59 => "diametr_shtoka",
            60 => "kalibr_mm",
            61 => "obshchiy_diametr",
            62 => "sila_natyazheniya",
            63 => "sovmestimye_modeli_pnevmaticheskikh_vintovok",
            64 => "model_tovara",
            65 => "skorost_puli_m_s",
            66 => "baza",
            67 => "ves_gr",
            68 => "ves_kg",
            69 => "ves_ballona_bez_ventilya_pustoy",
            70 => "davlenie_nakachki",
            71 => "dlinna",
            72 => "dlinna_mm",
            73 => "dlinna_sm",
            74 => "dlina_shlanga",
            75 => "nachalnaya_skorost",
            76 => "obshchaya_dlinna",
            77 => "razmer",
            78 => "vnutrenniy_diametr",
            79 => "diametr_sm",
            80 => "diametr_trubki_mm",
            81 => "mladshie_hatsan_55_60_70_8x_9x_100_105",
            82 => "moshchnost",
            83 => "rasstoyanie_mezhdu_osyami",
            84 => "rastyazhka",
            85 => "tsvet",
            86 => "diametr_obektiva_mm",
            87 => "dlina_ot_osi_do_osi",
            88 => "massa_puli_gramm",
            89 => "material",
            90 => "material_priklada",
            91 => "rabochee_davlenie",
            92 => "rabochiy_khod_tetivy",
            93 => "starshie_hatsan_125_135_150_155",
            94 => "dlina_strely",
            95 => "kratnost_uvelicheniya",
            96 => "maksimalnoe_davlenie",
            97 => "massa_puli_gran",
            98 => "nachalnaya_skorost_strely_m_s",
            99 => "rekomenduemaya_periodichnost_profilaktik",
            100 => "tip_vzvedeniya",
            101 => "gabarity",
            102 => "material_ballona",
            103 => "nalichie_podsvetki",
            104 => "sila_natyazheniya_kg",
            105 => "dlinna_vintovki_mm",
            106 => "zaryadnost",
            107 => "ispolzuemye_boepripasy",
            108 => "manometr",
            109 => "massa",
            110 => "sbros",
            111 => "v_komplekt_vkhodit",
            112 => "dlina_vintovki_mm",
            113 => "komplektatsiya",
            114 => "obem",
            115 => "tip_pistoleta",
            116 => "ves_porozhnego_ballona_s_ventilem",
            117 => "dlina_strely_dyuym",
            118 => "tip_vintovki",
            119 => "tip_pul",
            120 => "ves_1_litra_vozdukha_pod_davleniem_300_atm",
            121 => "material_korpusa",
            122 => "tip_pritsela",
            123 => "dlina_s_ventilem",
            124 => "diametr",
            125 => "srok_sluzhby",
            126 => "proizvoditel",
            127 => "strana_proizvoditel",
            128 => "vote_count",
            129 => "rating",
            130 => "vote_sum",
            131 => "naznachenie_vint",
            132 => "kalibr_vint",
            133 => "skorost_pyli_ms_vint",
            134 => "ves_kg_vint",
            135 => "material_priklada_vint",
            136 => "tip_vintovki_vint",
            137 => "tip_vzvedeniya_vint",
            138 => "zaryadnost_vint",
            139 => "emkost_zaryadnogo_ustroystva_vint",
            140 => "dlina_sm_vint",
            141 => "dlina_stvola_sm_vint",
            142 => "tip_priklada_vint",
            143 => "tip_rykoyati_vint",
            144 => "istochnik_energii_vint",
            145 => "tip_pricelnogo_prisposoblenia_vint",
            146 => "opticheskii_pricel_vint",
            147 => "kollimatornii_pricel_vint",
            148 => "otkritii_pricel_vint",
            149 => "baza_kreplenia_optiki_vint",
            150 => "proizvoditel_vint",
            151 => "strana_proizvoditel_vint",
            152 => "komplectaciya_vint",
            153 => "boevoi_analo_pist",
            154 => "kalibr_pist",
            155 => "skorost_puli_pist",
            156 => "ves_kg_pist",
            157 => "material_korpusa_pist",
            158 => "podvijnost_zatvora_pist",
            159 => "blowback_pist",
            160 => "zaryadnost_pist",
            161 => "tip_pistoleta_pist",
            162 => "tip_stvola_pist",
            163 => "tip_boepripasov_pist",
            164 => "emkost_magazina_pist",
            165 => "zatvornaya_zaderjka_pist",
            166 => "avtomaticheskii_rejim_strelbi1_pist",
            167 => "istochnik_energii_pist",
            168 => "naznachenie_pist",
            169 => "proizvoditel_pist",
            170 => "strana_proizvoditel_pist",
            171 => "opves_pist",
            172 => "komplectaciya_pist",
            173 => "yvelichenue_binokl",
            174 => "Pole_zrenia_binokl",
            175 => "Diametr_vyhodnogo_zrachka_mm_binokl",
            176 => "Ydalenie_vyhodnogo_zrachka_binokl",
            177 => "tip_binokl",
            178 => "Sistema_fokysirovki_binokl",
            179 => "Vid_prizm_binokl",
            180 => "Steklo_prizm_binokl",
            181 => "cvet_binokl",
            182 => "ves_gr_binokl",
            183 => "boevoy_prototip_signal_pist",
            184 => "kalibr_pyli",
            185 => "ves_gramm_pyli",
            186 => "ves_gran_pyli",
            187 => "tip_pyli",
            188 => "material_pyli",
            189 => "naznachenie_pyli",
            190 => "brand_pyli",
            191 => "strana_proizvoditel_pyli",
            192 => "dlina_sm_keysy",
            193 => "vneshniy_material_keysy",
            194 => "vnytrenniy_material_keysy",
            195 => "vmestimost_keysy",
            196 => "vysota_sm_keysy",
            197 => "forma_keysy",
            198 => "tip_perenoski_keysy",
            199 => "karmany_keysy",
            200 => "dopolnitelno_keysy",
            201 => "brand_keysy",
            202 => "strana_proizvoditel_keysy",
            203 => "tip_kobury",
            204 => "material_kobury",
            205 => "dopolnitelno_kobury",
            206 => "brand_kobury",
            207 => "strana_proizvoditel_kobury",
            208 => "kratnost_optika",
            209 => "minimalnoe_opticheskoe_uvelichenie_optika",
            210 => "maksimalnoe_opticheskoe_uvelichenie_optika",
            211 => "podsvetka_optika",
            212 => "diametr_obektiva_mm_optika",
            213 => "otstroyka_parallaksa_optika",
            214 => "diametr_trybki_mm_optika",
            215 => "tip_setki_optika",
            216 => "gravirovannaya_setka_optika",
            217 => "dlina_mm_optika",
            218 => "ves_gr_optika",
            219 => "otstroyka_pod_dioptrii_glaza_optika",
            220 => "brand_optika",
            221 => "strana_proizvoditel_optika",
            222 => "kalibr_shariki",
            223 => "ves_gr_shariki",
            224 => "material_shariki",
            225 => "brand_shariki",
            226 => "strana_proizvoditel_shariki",
            227 => "tip_arbaleta_arbalety",
            228 => "naznachenie_arbalety",
            229 => "skorost_arbalety",
            230 => "usilie_natyazhenia_kgs_arbalety",
            231 => "pricelnaya_dalnost_m_arbalety",
            232 => "rabochiy_hod_tetivy_arbalety",
            233 => "raznah_plechei_arbalety",
            234 => "dlina_so_stremenem_arbalety",
            235 => "ves_kg_arbalety",
            236 => "pricelnaya_planka_arbalety",
            237 => "standart_boltov_duym_arbalety",
            238 => "vid_plechei_arbalety",
            239 => "garantiya_arbalety",
            240 => "komplektacya_arbalety",
            241 => "brand_arbalety",
            242 => "tip_luka_luki",
            243 => "naznachenie_luki",
            244 => "vozrastnaya_kategoriya_luki",
            245 => "skorost_luki",
            246 => "usilie_natyazhenia_kgs_luki",
            247 => "pricelnaya_dalnost_m_luki",
            248 => "dlina_rastyagki_luki",
            249 => "sbros_usiliya_luki",
            250 => "ves_luki",
            251 => "dlina_luka_luki",
            252 => "standart_strel_luki",
            253 => "komplektaciya_luka_luki",
            254 => "material_rukoyati_luki",
            255 => "material_plechey_luki",
            256 => "dominantnost_ruk_luki",
            257 => "razborny_luki",
            258 => "brand_luki",
            259 => "garantiya_luki",
            260 => "chastota_obnovlen_cadrov_teplovizor",
            261 => "tip_displeya_teplovizor",
            262 => "razreshenie_displeya_pics_teplovizor",
            263 => "razmer_picselya_teplovizor",
            264 => "kratnost_teplovizor",
            265 => "diametr_obektiva_teplovizor",
            266 => "min_distanciya_focusirovki_teplovizor",
            267 => "typ_elementov_pitaniya_teplovisor",
            268 => "resurs_batarei_teplovizor",
            269 => "klass_zashishennosti_teplovizor",
            270 => "temperaturniy_diapazon_teplovizor",
            271 => "udarostoykost_teplovizor",
            272 => "razmer_teplovizor",
            273 => "brand_teplovizor",
            274 => "strana_proizvoditel_teplovizor",
            275 => "komplektaciya_teplovizor",
            276 => "proizvoditel_vse_tovary",
            277 => "ves_dalnomer",
            278 => "razmery_dalnomer",
            279 => "4549",
            280 => "yvelichenue_dalnomer",
            281 => "diaoazon_izmerenia_dalnomer",
            282 => "Tochnost_izmerenia_dalnomer",
            283 => "cvet_dalnomer",
            284 => "Vodonepronicaemost_dalnomer",
            285 => "Vid_prizm_dalnomer",
            286 => "Sistema_fokysirovki_dalnomer",
            287 => "Steklo_prizm_dalnomer",
            288 => "razreshenie_microbolometra_teplovizor",
            289 => "tip_mikrobolometra_teplovizor",
            290 => "min_opticheskoe_uvelichenie_teplovizor",
            291 => "max_opticheskoe_uvelichenie_teplovizor",
            292 => "cifroviy_zoom_teplovizor",
            293 => "regim_pip_teplovizor",
            294 => "nabor_cvetovih_shem_teplovizor",
            295 => "pole_zreniya_teplovizor",
            296 => "udaleniye_ot_zrachka_teplovizor",
            297 => "nastroyka_dioptriy_teplovizor",
            298 => "dalnost_obnarugeniya_teplovizor",
            299 => "lazer_dalnomer_teplovizor",
            300 => "kolvo_konfigy_pricelnoy_setki_teplovizor",
            301 => "napryagenie_pitaniya_teplovizor",
            302 => "vneshnee_pitanie_teplovizor",
            303 => "energosber_regim_teplovizor",
            304 => "podkluch_vneshnego_istochnika_teplovizor",
            305 => "ves_bez_elementov_pitaniya_teplovizor",
            306 => "cena_klika_teplovizor",
            307 => "zapas_hoda_metki_teplovizor",
            308 => "vlagozashita_teplovizor",
            309 => "becshumniy_regim_nastroek_teplovizor",
            310 => "zapominanie_pricelnih_tochek_teplovizor",
            311 => "pristrelka_odnim_vistrelom_teplovizor",
            312 => "freeze_teplovizor",
            313 => "funkciya_otklucheniya_displeya_teplovizor",
            314 => "besprovodnoy_pult_teplovizor",
            315 => "tip_planki_teplovizor",
            316 => "komplektaciya_acsessuary_teplovizor",
            317 => "",
        ),
        "COMPARE_ELEMENT_SORT_FIELD" => "sort",
        "COMPARE_ELEMENT_SORT_ORDER" => "asc",
        "DISPLAY_ELEMENT_SELECT_BOX" => "N",
        "COMPARE_POSITION_FIXED" => "Y",
        "COMPARE_POSITION" => "top left",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "STATIC",
        "DETAIL_SHOW_BASIS_PRICE" => "Y",
        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
        "PRODUCT_DISPLAY_MODE" => "N",
        "OFFER_ADD_PICT_PROP" => "-",
        "OFFER_TREE_PROPS" => array(
            0 => "COLOR",
            1 => "SIZE",
            2 => "COLOR2",
        ),
        "USER_CONSENT" => "N",
        "USER_CONSENT_ID" => "0",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "N",
        "DETAIL_STRICT_SECTION_CHECK" => "N",
        "FILTER_OFFERS_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "FILTER_OFFERS_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "COMPARE_OFFERS_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "COMPARE_OFFERS_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "OFFERS_CART_PROPERTIES" => array(
        ),
        "TOP_OFFERS_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "TOP_OFFERS_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "TOP_OFFERS_LIMIT" => "5",
        "LIST_OFFERS_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "LIST_OFFERS_PROPERTY_CODE" => array(
            0 => "",
            1 => "",
        ),
        "LIST_OFFERS_LIMIT" => "5",
        "DETAIL_OFFERS_FIELD_CODE" => array(
            0 => "",
            1 => "",
        ),
        "DETAIL_OFFERS_PROPERTY_CODE" => array(
            0 => "COLOR",
            1 => "SIZE",
            2 => "COLOR2",
        ),
        "OFFERS_SORT_FIELD" => "sort",
        "OFFERS_SORT_ORDER" => "asc",
        "OFFERS_SORT_FIELD2" => "id",
        "OFFERS_SORT_ORDER2" => "desc",
        "COMPATIBLE_MODE" => "Y",
        "SEF_URL_TEMPLATES" => array(
            "sections" => "",
            "section" => "#SECTION_CODE_PATH#/",
            "element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
            "compare" => "compare/",
            "smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
        )
	),
	false
);?>
<div class="help_form_bl">
    <div class="help_form_l">
        <img data-src="/img/help_form_ic.png"/>
    </div>
    <div class="help_form_r prume_form">
		
    </div>
</div>
<div class="f_advantages_bl">
    <div class="f_advantages_el">
        <div class="f_advantages_ic"><img data-src="/img/f_advantages_ic1.png" alt=""/></div>
        <div class="f_advantages_txt">Качественные <br/>товары</div>
    </div>
    <div class="f_advantages_el">
        <div class="f_advantages_ic"><img data-src="/img/f_advantages_ic2.png" alt=""/></div>
        <div class="f_advantages_txt">Удобство <br/>выбора</div>
    </div>
    <div class="f_advantages_el">
        <div class="f_advantages_ic"><img data-src="/img/f_advantages_ic3.png" alt=""/></div>
        <div class="f_advantages_txt">Широкий <br/>ассортимент</div>
    </div>
    <div class="f_advantages_el">
        <div class="f_advantages_ic"><img data-src="/img/f_advantages_ic4.png" alt=""/></div>
        <div class="f_advantages_txt">Дополнительная <br/>гарантия</div>
    </div>
    <div class="f_advantages_el">
        <div class="f_advantages_ic"><img data-src="/img/f_advantages_ic5.png" alt=""/></div>
        <div class="f_advantages_txt">Доставка по России <br/>и странам ТС</div>
    </div>
</div>
<?
/*
?>
<div class="premme">
    <div class="prume_form"></div>
    <div style="clear: both"></div>
    <div class="premue_block display_none_m display_none_mp display_none_p">
        <a href="/otziv/">
        <div class="premue_item"><div class="premue_img"><img src="/images/pr/1.png"></div>
            Качественные <br>товары
        </div>
        </a>
        <a href="/help/kak-zakazat/">
        <div class="premue_item"><div class="premue_img"><img src="/images/pr/2.png"></div>
            Удобство <br> выбора
        </div>
        </a>
        <a href="/catalog/">
        <div class="premue_item"><div class="premue_img"><img src="/images/pr/3.png"></div>
            Широкий <br>ассортимент
        </div>
        </a>
        <a href="/garantii/">
        <div class="premue_item"><div class="premue_img"><img src="/images/pr/4.png"></div>
            Дополнительная <br>гарантия
        </div>
        </a>

        <a href="/delivery/">
        <div class="premue_item"><div class="premue_img"><img src="/images/pr/5.png"></div>
            Доставка по России <br>и странам ТС
        </div>
        </a>

    </div>
</div>
<?  
*/
?>
    <style>.premue_block a{text-decoration:none;}</style>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>